### ISSUE TITLE
 Publicar en Google Play 

### ISSUE THREAD

**Issue by epd1002** [epd1002/GESPRO_GESTION_DE_TAREAS#10]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by elisarodriguez0** [comment]
![imagen](https://user-images.githubusercontent.com/58004666/73264879-12a69280-41d4-11ea-8941-a633234da8cb.png)
![imagen](https://user-images.githubusercontent.com/58004666/73264901-1afecd80-41d4-11ea-9eb5-7390efb1c960.png)
![imagen](https://user-images.githubusercontent.com/58004666/73264912-205c1800-41d4-11ea-9638-5aa9cf932f9a.png)
![imagen](https://user-images.githubusercontent.com/58004666/73264929-2e119d80-41d4-11ea-96bf-eb3b25394c73.png)
![imagen](https://user-images.githubusercontent.com/58004666/73264943-336ee800-41d4-11ea-910a-ad71de4256cc.png)
![imagen](https://user-images.githubusercontent.com/58004666/73264952-38339c00-41d4-11ea-8567-7f702b475fb6.png)

**Comment by elisarodriguez0** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
